### ISSUE TITLE
GrblCNC does not work in locales with decimal separator different from .

### ISSUE THREAD

**Issue by terjeio** [shaise/GrblCNC#1]
In Norway we use `,` (comma) as decimal separator - and grbl is not happy about that:

![bilde](https://user-images.githubusercontent.com/20260062/77858559-9ac10c80-7204-11ea-94ac-054f35f96cdc.png)

I am using extension methods to fix that, here is one example:

```
        public static string ToInvariantString(this double value)
        {
            return value.ToString(CultureInfo.InvariantCulture);
        }
```

**Comment by shaise** [comment]
Thanks! noted.
Should I use it in the gcode sender only, or do it on the Mdi window as well?

**Comment by terjeio** [comment]
I think it is best to keep the format consistent, IIRC all senders I have used does that.

**Comment by shaise** [comment]
So, you think even on the PC display it should be ".", not only on grbl?
![bignum](https://user-images.githubusercontent.com/5813568/77890310-f4165380-7277-11ea-8773-83dab885e2f6.png)
(sorry for asking many questions)

**Comment by terjeio** [comment]
Yes I think that is best - to avoid ambiguity. If not users may believe it is ok to enter MDI commands or make programs with a decimal separator that is not accepted. Also, if the UI allows copy/paste you need to handle conversion when copying numerical data to the clipboard?

**Comment by shaise** [comment]
Ok. I have updated (hopefully) everything to use invariant culture.
Regarding Copy/Paste, I will add to the ToDo list. 
Thanks! this is very helpful
