### ISSUE TITLE
How to choose serial port to connect to?

### ISSUE THREAD

**Issue by terjeio** [shaise/GrblCNC#3]
I have 19 serial ports on my machine, app seems to connect on the first it manages to open and hang if this does not respond to queries. A timeout is required? Or explicit configuration?

**Comment by shaise** [comment]
There should be a timeout of no reply, and then it should skip to the next. I will check it again. I plan to add manual selection as well.

**Comment by shaise** [comment]
Ok, In my system I have 3 ports, and it skips the ports that are not grbl (they can be opened) and connects to the grbl one. I wonder why is it hang in yours.
When I implement the sender settings, I will add manual setting of com port.

B.T.W, What is the best way to stop a running gcode job completely? (not just pause). Right now I issue a pause, then a soft reset. Not sure its the best way.

**Comment by terjeio** [comment]
Ok, checked a bit more on my end. Timeout seems to be working but when sending a soft reset to a bluetooth port with no endpoint active(?) the `SendByte(CMD_SOFT_RESET);` never returns. I guess this blocks the timeout as well?

This is the offending port:

![bilde](https://user-images.githubusercontent.com/20260062/79040033-f5d00780-7be5-11ea-929a-f80ec42a1d7d.png)

A bunch ofther similar bluetooth ports get skipped since the `port.Open()` command fails for them.
Strange...

**Comment by terjeio** [comment]
As for stopping a job that depends on whether for grbl or grblHAL. I have added a stop realtime command to grblHAL since I do not always want to issue a reset - IMO a bit harsh. In my sender I handle this differently depending on which firmware is in use and also depending on the app setting for aggresive buffering.

You may [peek at what I have done](https://github.com/terjeio/Grbl-GCode-Sender/blob/master/CNC%20Controls/CNC%20Controls/JobControl.xaml.cs) if interested.

**Comment by shaise** [comment]
Thanks for the stop-job hints.
For the blocking write to ports, can you try adding the following line to open port and see if this helps?
![serial_timeout](https://user-images.githubusercontent.com/5813568/79040918-97f6ec00-7bf4-11ea-885d-ebd8d349547a.jpg)

**Comment by terjeio** [comment]
Thanks, that fixed it.

BTW, the jog artefact you showed me before is not visible with your latest version and an unpatched version of grblHAL (for MSP432)...

**Comment by shaise** [comment]
Thank you, I have committed this fix.
